name: logger_flutter_ns_v1
description: A simple plug & play flutter logger console. You can use this plugin for logging on ide or by shaking your phone to see logs on phone.
version: 1.0.2
homepage: https://github.com/mehmetarsay/logger_flutter_ns

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^2.6.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  sensors_plus: ^7.0.0
dev_dependencies:
  test: ^1.26.3